url = "http://124.71.204.213/auto_api/api/cita-cloud-test/send_tx"

[headers]
user_code = "test-user-1"
request_key = "<request_key:SeqNum>"
version = "v1.2.0"

[body]
to = "0x164f225d70805e94f5179eb1a523c5796e68893b"
data = "0x1e2fc4f7"
gas = 2000000
